version: "2"

services: 
  
  mongo:
    image: mongo:3.4.0
    volumes: 
      - "./data:/data/db"
  
  web:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    working_dir: /app
    command: nodemon -L /app/bin/www
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
    environment: 
      - DB_SERVER=mongo
      - NODE_ENV=development